version: 2.1
jobs:
  my-job-name:
    working-directory: ~/my-project
    docker:
      - image: circleci/node:10-browsers    
    steps:
      - checkout
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install