version: 2.1
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:14-browsers    
    steps:
      - checkout
      - run: npm install
      - run: npm run test --no-watch --no-progress --browsers=ChromeHeadlessCI